### ISSUE TITLE
SSL?

### ISSUE THREAD

**Issue by photex** [H2CO3/avocado#7]
There doesn't seem to be a feature or any documentation for SSL connections. Is that by design or does SSL just work if you need to use it?

**Comment by H2CO3** [comment]
I don't think Avocado needs to be involved in that, since this applies at a lower level, to an entire MongoDB connection, and it can be directly set in the client, e.g. `Client::with_uri("mongodb://localhost:27017?ssl=true")`. I'd assume that if you use any database and collection coming from such a client (e.g. by requesting one wrapped in an Avocado collection) then it would just use SSL.
